# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json
PackageIdentifier: ChaosStudio.ChaosLauncher
PackageVersion: 1.0.9
PackageLocale: es-ES
Publisher: Chaos Studio
PublisherUrl: https://github.com/LuisEnriqueGM03
PackageName: Chaos Launcher
PackageUrl: https://github.com/LuisEnriqueGM03/Chaos-Launcher-Esc
License: Proprietary
Copyright: Copyright © 2026 Chaos Studio. Todos los derechos reservados.
ShortDescription: Launcher de Minecraft con soporte premium y no premium y modpacks con actualización automática.
Tags:
- minecraft
- launcher
- modpack
ManifestType: defaultLocale
ManifestVersion: 1.6.0
